### ISSUE TITLE
Enable queries on individual tables during start up vs server-wide

### ISSUE THREAD

**Issue by jugomezv** [apache/pinot#10095]
During recent work we found that queries are disabled server-wide for all tables during catch up stage. The goal of this issue is to study how hard it would be to enable queries on a per table basis instead (during startup). The plus of this would be that some tables with low rate of events will not have to be subject to "convoy" effect due to high rate consumption tables and those tables with low rate will become available early during startup of the server contributing to increased availability.

**Comment by mcvsubbu** [comment]
The queries are disabled not just due to consumption catch up. In fact, the consumption part was added much later. The original intent (and that is still there) to hold queries was to make sure that all the segments assigned to the server are loaded and in ONLINE state. 

The number of CONSUMING segments (that need to do the event catchup) are usually a small fraction of the total number of segments in a host.

**Comment by jugomezv** [comment]
OK but still it would make sense to have this signal right: all segments for this table are ready to be queried

**Comment by Jackie-Jiang** [comment]
The reason why we only enable queries when all tables are ready is because we don't want server to start serving queries when it is still bulk loading the segments because segment loading the take a lot of system resources. Without the extra control, pinot can route queries on segment level (start serving a segment whenever it is loaded), but that is not desired due to the same reason.

**Comment by jugomezv** [comment]
OK so may be this is not a good idea after all right? So I guess the side affect of a change like this is that we could even slow further the loading of segments in tables that are slow in the first place and then feed a spiral of delay. I see now, closing then.
