### ISSUE TITLE
JSON_MATCH filter ignores value type

### ISSUE THREAD

**Issue by jackluo923** [apache/pinot#10360]
In the official Pinot documentation's JSON index [page](https://docs.pinot.apache.org/basics/indexing/json-index#value), the example hints that the boolean expression's right hand side can be either a STRING type (`'"<json path>"=''<string>'''`), INT type (`'"<json path>"=<int>'`) and FLOAT type (`'"<json path>":<float>'`). In reality, Pinot does not differentiate data type inside `JSON_MATCH` filter.

Take the following table content as an example: 
```
----------------
| JSON_COL      |
----------------
| {"key": 1}    |
----------------
| {"key": "1"}  |
----------------
```

The following query would match **both** rows above: 
```
SELECT * FROM TABLE WHERE CLP_MATCH("JSON_COL", '"$.key"=''1''')
```

If the JSON_MATCH filter applies type-specific filter, then we only expect `{"key": "1"}` to be returned.

**Is this a bug or a feature?** Can we expect this behavior to stay as-is for the foreseeable future?

**Comment by Jackie-Jiang** [comment]
Good question. This behavior is due to how we store key-value pair in JSON index, where value is always appended without quotes.
In order to change this, we can consider introducing a new JSON index version, where we put quotes over the value if it is a string.
We will keep the current behavior for the current JSON index version for backward compatible

**Comment by jackluo923** [comment]
Great! In our search workload, we do not know type of the tokens which we want to use in JSON_MATCH. Having JSON_MATCH that ignores the data type allow us to simplify our query thus working in our favor. 👍
