### ISSUE TITLE
Partial Upsert table ingestion stops after server restarts

### ISSUE THREAD

**Issue by tibrewalpratik17** [apache/pinot#10552]
We have a partial upsert table. The ingestion of the partial upsert table stopped after the server restarts. This can potentially be caused due to #10198. This is seen for tables with out-of-order events.

Thread dump shows the thread stuck at this:
```
java.lang.Thread.State: TIMED_WAITING (sleeping)
--
at java.lang.Thread.sleep(java.base@11.0.15/Native Method)
at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager.consumeLoop(LLRealtimeSegmentDataManager.java:400)
at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager$PartitionConsumer.run(LLRealtimeSegmentDataManager.java:633)
at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)
```

After the server restarts, the consuming segment messages are replayed. But in our case there is a record which comes out of order after which the replaying gets stuck in the above `consumeLoop` method.

This was the original log message during normal consumption. 
```
current comparison value: 1680617590, record comparison value: 1680617589), skipping updating the record
```
After this, I see consuming messages logs during the entire day but just after the server restart, there is no record beyond the timestamp of this log showing reloading the segment failed.

I see logs of `No events came in, extending time by 1 hours` every one hour for this table.

**Comment by tibrewalpratik17** [comment]
cc @Jackie-Jiang

**Comment by Jackie-Jiang** [comment]
Trying to understand the issue here. Are you running the latest code with #10198 fix? If so, this can happen when some segments cannot be loaded. You want to check the external view of the table and see if some segments are running into ERROR state. For partial-upsert table, we can start consuming only when all the segments are properly loaded

**Comment by tibrewalpratik17** [comment]
Trying out this fix #10204 and checking if it works or not!

**Comment by navina** [comment]
@zhtaoxiang : can you pick up this issue, in case there is more follow-up/debugging to do?

**Comment by ankitsultana** [comment]
@Jackie-Jiang : We saw this again today for one of our clusters. I saw this:

1. In the logs there was a message for the 235th segment of the a Kafka partition:

```
2023-04-18 06:31:11.871 [my_table__224__236__20230418T0520Z] INFO  o.a.pinot.segment.local.utils.tablestate.TableStateUtils  - Found 1 unloaded segments: [my_table__64__235__20230417T2021Z] for table: my_table_REALTIME
```

2. In the thread-dump I saw that the consumeLoop had started consuming for the 236th segment already and was waiting on all segments to be loaded:

```
"my_table_v3__64__236__20230418T0511Z" #1992 daemon prio=5 os_prio=0 cpu=1911.79ms elapsed=4383.52s tid=0x00007efb10016800 nid=0x967 waiting on condition  [0x00007ee0714fa000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(java.base@11.0.15/Native Method)
        at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager.consumeLoop(LLRealtimeSegmentDataManager.java:406)
        at org.apache.pinot.core.data.manager.realtime.LLRealtimeSegmentDataManager$PartitionConsumer.run(LLRealtimeSegmentDataManager.java:647)
        at java.lang.Thread.run(java.base@11.0.15/Thread.java:829)
```

This seems like a deadlock. We can't even reset segments to get out of this since it gets stuck in acquiring the `_partitionGroupConsumerSemaphore`

**Comment by Jackie-Jiang** [comment]
@ankitsultana is the 235th segment trying to transfer from `OFFLINE` to `CONSUMING` state? If so, that might explain the deadlock. When server starts consuming the 236th segment, 235th segment should be already in `ONLINE` state in ideal state. But server side might still be processing the `OFFLINE` to `CONSUMING` state, which is blocked by 236th segment because we only allow one consuming segment at the same time

**Comment by snleee** [comment]
https://github.com/apache/pinot/pull/10928 <- this PR has been merged from
