### ISSUE TITLE
TableName extraction fails for tables with name pattern as `db.tablename` in CalciteSqlParser

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#10701]
[extractTableNamesFromNode](https://github.com/apache/pinot/blob/master/pinot-common/src/main/java/org/apache/pinot/sql/parsers/CalciteSqlParser.java#L144) extracts incorrect name for the table with a pattern like `db.tablename`.

Instead of extracting the full name as one value, it's outputting two values. Example query
```
Select * from db.tbl1
```
It extracts a List with 2 elements (1. 'db', 2. 'tbl1')

`SqlNodeAndOptions` for the above query has two values in the `FROM` node.
<img width="1455" alt="Screen Shot 2023-04-28 at 7 25 09 PM" src="https://user-images.githubusercontent.com/1076944/235269232-45adcf1d-a19c-4bef-a210-e5f7db7fc6f0.png">

Just confirming, is it suppose to be like this? 

cc @walterddr @ankitsultana @tibrewalpratik17

**Comment by ankitsultana** [comment]
From Calcite's perspective this is correct and you can refer to `RelOptTable`.

I am not sure if we allow dot separated table names in Pinot.

**Comment by abhioncbr** [comment]
> From Calcite's perspective this is correct and you can refer to `RelOptTable`.
> 
> I am not sure if we allow dot separated table names in Pinot.

Thanks for the confirmation. 
I came to know about this because one of the integration [test case failed](https://github.com/apache/pinot/blob/master/pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/OfflineClusterIntegrationTest.java#L2367) with the usage of the above method.

**Comment by walterddr** [comment]
this is actually not suppose to work. to a complete SQL system `db.table1` means `{"catalog": "db", "table": "table1"}` 
however pinot doesn't support catalog thus any prepended catalog is resolved as "default" thus the integration test case is to verify that for the existing query engine. 

However for the new engine, we actually implicitly added the default catalog name since Calcite's catalog reader requires a root schema (or root catalog if you will) thus it will not be able to find a `db` catalog internally. 

We are yet to discuss the catalog support going forward but as far as for now this will not be supported as "ignoring the catalog and only parse table name, then move on with what we had" is not really something we should do

**Comment by navina** [comment]
@walterddr : is there an action item on this issue? 

follow-up question: Have we already documented the rules / requirements for a pinot table resource somewhere?

**Comment by walterddr** [comment]
- I don't think so at this moment. we can continue discussion this thread on how to support catalog going forward. 
- I couldn't find a single reference to `db.tbl` or `catalog.tbl` in pinot official doc. so the usage pattern is probably just "worked unintentionally" and ppl start using it. and I am not sure this is the pattern we want to do going forward 
- we can check how other ANSI SQL system works with catalog but AFAIK I don't think any will 'fallback to default catalog if tbl name is missing'

**Comment by shounakmk219** [comment]
@abhioncbr  The mentioned issue should be addressed by https://github.com/apache/pinot/pull/12591
Tagging @gortiz as well.
