### ISSUE TITLE
Performance Benchmark

### ISSUE THREAD

**Issue by tridib** [apache/pinot#12]
It's great work. Thanks for making available to public.
Have you done any benchmarking? I like to what kind of hardware do I need to run analytical query in sub-second time over n billion records. Trying to get a ballpark figure.

**Comment by makareth** [comment]
At this time, no Google search yields any information regarding the performance of the product. Setting up a benchmark result page would be great indeed.

**Comment by kishoreg** [comment]
Hi,

Unfortunately the numbers we have cannot be shared since they represent
LinkedIn data. We are working on using tpch data and will update you once
we have that.

You will definitely need to keep the data in memory to get sub second
response time. Assuming average speed of 40 to 50 million documents per
second (note this also depends on the number of columns specified in the
query), you should be able to get this in 2 or 3 boxes for 1 billion
documents (This depends on the number of columns and column type).

In most cases, these numbers depends on the data and query pattern. We
apply various optimization techniques depending on the use case. If you can
provide additional details such as schema, query pattern we can definitely
help you come up with the right configuration.

thanks,
Kishore G
