### ISSUE TITLE
Remove BOOLEAN data-type field check for deleteRecordColumn

### ISSUE THREAD

**Issue by tibrewalpratik17** [apache/pinot#12217]
For Point-deletes in Upserts to work, we enforce that the column field to be Boolean type field here - https://github.com/apache/pinot/blob/d1cc17c5792b6284b29f7ed05a3dea01ac27ca29/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/utils/TableConfigUtils.java#L729-L734

But during the time of ingestion, we use `BooleanUtils` class to extract boolean value from the column field -- https://github.com/apache/pinot/blob/d1cc17c5792b6284b29f7ed05a3dea01ac27ca29/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/indexsegment/mutable/MutableSegmentImpl.java#L562

Do we necessarily need the first check in `TableConfigUtils` that the field should be BOOLEAN? This way we can have values as String-based "true"/"false", "0"/"1" ...

cc @navina @Jackie-Jiang @ankitsultana

**Comment by walterddr** [comment]
what's the motivation behind removing this check? the deleteRecordColumn should be a "system managed" column and thus setting it as boolean should be reasonable. unless this field can also be modified in other codepath.

**Comment by navina** [comment]
> what's the motivation behind removing this check? the deleteRecordColumn should be a "system managed" column and thus setting it as boolean should be reasonable. unless this field can also be modified in other codepath.

+1 to @walterddr 's question. Why do you need to support non-boolean type values like 0/1 etc?

**Comment by ankitsultana** [comment]
For context, we have some customers internally whose Kafka topics have string and int columns for indicating the deleted column field. Changing topic schema isn't trivial. We could use ingestion transforms but wanted to avoid that due to maintenance reasons (we generally discourage this internally due to some operational concerns).

My take on this was: the `deleteRecordColumn` will be used to infer a boolean decision (whether a record is deleted or not). If the column happens to be some other type like string or int, then the usual type coercion rules can be applied. (as defined in BooleanUtils).

I feel this way we can still keep the behavior intuitive and reasonable.

**Comment by tibrewalpratik17** [comment]
> For context, we have some customers internally whose Kafka topics have string and int columns for indicating the deleted column field. Changing topic schema isn't trivial. 

+1 to @ankitsultana's comment. Some of our customers already publish the delete fields as string and int columns; and asking them to move to boolean has a lot of operational overhead. I tried out this #12222 patch with one of the topics where String "true" / "false" was being published and it worked out fine!

**Comment by walterddr** [comment]
ok so that's not the original intend of this `deleteRecordColumn` right @navina ? IIUC this is not suppose to be modified by user during ingestion

**Comment by navina** [comment]
> For context, we have some customers internally whose Kafka topics have string and int columns for indicating the deleted column field. Changing topic schema isn't trivial.

This requirement makes sense as changing topic schema is not trivial and ingestion transforms can help circumvent these issues. 

>  If the column happens to be some other type like string or int, then the usual type coercion rules can be applied.

@ankitsultana How does the type coercion rule work when in the input string is unexpected? I haven't looked into pinot's mechanism of handling type coercion for its config values. Is it actually being used during config parsing? 

> that's not the original intend of this deleteRecordColumn right @navina ? IIUC this is not suppose to be modified by user during ingestion

The intention of adding the check was to make sure that the users are not misconfiguring it. This can be system-managed in case of CDC connectors or user-managed in other stream connectors. It is a user-facing config, iirc. 

@ankitsultana / @tibrewalpratik17  If you can add more validation in the TableConfigUtils for this config, instead of strict type check, I am fine with that. Blindly removing the check is a bit much.

**Comment by walterddr** [comment]
if the field is intended to be modified by user i think it is reasonable for the type change IMO

b/c transform function are applied after upsert occurs (IIUC) this means if user wanted to convert a source field from the stream connector to a boolean type then write it into the upsert delete record column, it is not possible. 

do we have any discussion regarding whether a derived field is transformed before or after upsert occurs?

**Comment by tibrewalpratik17** [comment]
> How does the type coercion rule work when in the input string is unexpected? I haven't looked into pinot's mechanism of handling type coercion for its config values. Is it actually being used during config parsing?


It throws an exception if it encounters anything other than Number, String, Boolean. In these datatypes, it defaults to false which should be the intent with `deleteRecordColumn`.
https://github.com/apache/pinot/blob/436968e080e89cdf4e08ab064e47cc70b1eb6491/pinot-spi/src/main/java/org/apache/pinot/spi/utils/BooleanUtils.java#L42-L54


>  If you can add more validation in the TableConfigUtils for this config, instead of strict type check, I am fine with that. Blindly removing the check is a bit much.

@navina any suggestions on this? Should we check for String and Number rather than removing Boolean as per coercion logic? 

> transform function are applied after upsert occurs (IIUC) this means if user wanted to convert a source field from the stream connector from its native type to a boolean type then write it into the upsert delete record column, it is not possible.

@walterddr are we sure about this? Then how does partial-upserts work? Before applying the transformation?

**Comment by walterddr** [comment]
> @walterddr` are we sure about this? Then how does partial-upserts work? Before applying the transformation?

Double checked and I think it's the other way around --> transform is always being applied before the upsert change is made to the previous valid row. So that seems to be a valid solution? E.g. if user have a schema that's not a Boolean column. We can always derive a Boolean column out and use that as the delete recordColunm. Will that solve your problem (schema change is required but it is addition, not type changes)

**Comment by tibrewalpratik17** [comment]
> So that seems to be a valid solution? E.g. if user have a kafka schema that's not a Boolean column. We can always derive a Boolean column out in Pinot schema and use that as the deleteRecordColunm. Will that solve your problem.
Schema change is required if the table is already created though.

Yes it is a valid solution. But lot of our tables are already created and now to apply schema change on them with transform config is really operational. So that's why we want to get rid of the type check config validation so that we can easily apply this config for existing tables as well.

**Comment by navina** [comment]
> > So that seems to be a valid solution? E.g. if user have a kafka schema that's not a Boolean column. We can always derive a Boolean column out in Pinot schema and use that as the deleteRecordColunm. Will that solve your problem.
> > Schema change is required if the table is already created though.
> 
> Yes it is a valid solution. But lot of our tables are already created with using string / int as deleted fields and now to apply schema change on them with transform config is really operational. So that's why we want to get rid of the type check config validation or extend it for String / Number so that we can easily apply this deleteRecordColumn config for existing tables as well.

nit: it will be a table config change, rather than a schema change in such a case.

**Comment by tibrewalpratik17** [comment]
Closing this as it is completed via #12222.
