### ISSUE TITLE
Consuming segment flush rows significantly reduced after force commit

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#12509]
When a segment is force committed with segment size based flush threshold enabled, I observed that the next consuming segment flush threshold (desired rows) are significantly reduced (reset to 10000). I feel there is a bug which is causing the size threshold not properly applied during force commit. cc @sajjad-moradi

**Comment by sajjad-moradi** [comment]
I believe as part of this [PR](https://github.com/apache/pinot/pull/12188/files), this issue was fixed.
Look here:
https://github.com/apache/pinot/blob/9cfce82385dfcd11eed4467c07f2409b76622d57/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/realtime/segment/SegmentFlushThresholdComputer.java#L82-L93
