### ISSUE TITLE
`createDictionaryForColumn` does not take into account inverted index

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#12635]
I think the issue starts in https://github.com/apache/pinot/blob/3397986ada9b3f978c7d3fa6492986414e4a11d4/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/creator/impl/SegmentColumnarIndexCreator.java#L142 We check if the column is `dictEnabledColumn` to ensure we can create the inverted index. In that function, we eventually hit https://github.com/apache/pinot/blob/41ec20996fdb540222e8fdec3816be59a19b04c1/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/index/dictionary/DictionaryIndexType.java#L227 where if you have `optimizeDictionary` set, it just determines if it makes sense to create the dictionary or not based on the estimated size. There's no consideration if the column has an index that requires the dictionary.

**Comment by npawar** [comment]
@deepthi912 want to give this a shot?

**Comment by deepthi-912** [comment]
Sure, I will check it out.

**Comment by deepthi912** [comment]
According to my understanding the dictEnabledColumn checks if columns are dictionary supported and not raw indexed. Since inverted index support it, it would return true. In json and text indexes we are not enabling dictionary support for better storage capabilities I imagine. So in such case, I feel this condition should be !originalConfig.getConfig(StandardIndexes.inverted()).isEnabled() || !dictEnabledColumn

@npawar @jadami10 correct me if my analysis is wrong here.

https://github.com/apache/pinot/blob/3397986ada9b3f978c7d3fa6492986414e4a11d4/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/segment/creator/impl/SegmentColumnarIndexCreator.java#L143

**Comment by jadami10** [comment]
Here's my understanding of what is valid, what the original function does, and what your new function does.

| dictEnabledColumn | invertedIndex | is valid | "dictEnabledColumn or !originalConfig.getConfig(StandardIndexes.inverted()).isEnabled() | "!originalConfig.getConfig(StandardIndexes.inverted()).isEnabled() or !dictEnabledColumn" |
| --- | --- | --- | --- | --- |
| true | true | true | true | false |
| true | false | true | true | true |
| false | false | true | true | true |
| false | true | false | false | true |

I believe the original check is correct based on the table above. It specifically only fails when we're not creating a dictionary for the column but want the inverted index.

> Since inverted index support it, it would return true. In json and text indexes we are not enabling dictionary support for better storage capabilities I imagine.

Inverted indices don't just support the dictionary index, they actively require it.

**Comment by deepthi912** [comment]
@npawar Yes, we can close this.
