### ISSUE TITLE
[Helm] Update Zookeeper Helm Chart to the latest version

### ISSUE THREAD

**Issue by piby180** [apache/pinot#13079]
We are still using version 9.2.7 of bitnami zookeeper helm chart which was released in 2022. 

We would like to update it to the latest version 13.0.0 
https://github.com/bitnami/charts/tree/main/bitnami/zookeeper#upgrading

**Comment by abhioncbr** [comment]
I think it's good to bump the Zookeeper chart to 13.0.0 since we are using Zookeeper 3.9.2 in pinot[[reference](https://github.com/apache/pinot/blob/b76653e1acbe82c6e6b09655c7cb5ab20bbea4c1/pom.xml#L144)]. 

Bitnami zookeeper [chart 12.0.0](https://github.com/apache/pinot/blob/b76653e1acbe82c6e6b09655c7cb5ab20bbea4c1/pom.xml#L144) onwards is based on zookeeper version 3.9.0
