### ISSUE TITLE
Pinot Controller leader re-election not triggered

### ISSUE THREAD

**Issue by cypherean** [apache/pinot#13990]
We faced an issue in production wherein the controller leader node went down but re-election was not triggered. This lead to segment upload errors for tables trying to commit a segment, instances being marked as unavailable for the segment and finally queries failing for the tables with segments unavailable error. 
Pinot version - 1.0.x

Timeline for this was as follows:
1. A GET call for a large table's segments' metadata `tables/<tablename>/segments/<segmentName>/metadata?columns=*` spawns ~75k threads. This cause a huge memory spike and heap to go out of memory (heap size being 128GB here), maybe crashing the node. We suspect it was because of reload status button which triggers the segment metadata call
![Screenshot 2024-09-12 at 7 11 38 PM](https://github.com/user-attachments/assets/e0f27b0b-8934-416e-b608-0a139aba7f96)

2. The node's 2 zk sessions time out at 17:19:56, the node tries to reestablish connection but it keeps emitting metrics as a leader until 17:29:x
![Screenshot 2024-09-12 at 7 11 05 PM](https://github.com/user-attachments/assets/e50bac7f-0d27-4c3b-9592-958ccb06ddc4)

3. The health check for node starts failing around 17:20:x, but standby controller nodes keep polling and getting failed leader's session ID as leader until 18:10 when we triggered a force replacement of error node
![Screenshot 2024-09-12 at 7 19 24 PM](https://github.com/user-attachments/assets/4ec05d8a-f92b-4650-afb5-91f95130602c)

```
Instance 123 is not leader of cluster production-cluster due to current session 702147796290178 does not match leader session 702147796290171
```

Ideally the re-election should've triggered around 17:20.

**Comment by Jackie-Jiang** [comment]
Controller leader election is managed by Helix, so you might get more help posting this to Apache Helix project.

On Pinot side, we should triage why a metadata fetch call can spawn 75k threads. It doesn't look correct to me

**Comment by tibrewalpratik17** [comment]
> On Pinot side, we should triage why a metadata fetch call can spawn 75k threads. It doesn't look correct to me

Yes we were able to find the root cause for this. We spawn one thread per segment in case of server-metadata fetch. Ref: https://github.com/apache/pinot/blob/266073eee0a56ae811c65cb0828cff294212aa48/pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java#L185-L194

Ideally we can do one call per server rather than one call per segment. 

Plus we also use an unbounded thread pool for submitting these calls per segment causing 75k threads to spawn: https://github.com/apache/pinot/blob/266073eee0a56ae811c65cb0828cff294212aa48/pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java#L254-L255

We can limit the number of threads in this pool to something reasonable.

I think what we are interested to know more is why didn't leader-election kick off even when zk-client session was lost. We will raise an issue in Helix and link it here. Thanks!

**Comment by cypherean** [comment]
We'll address the above issues:
- [x] Reduce the threads spawned in API from no of segments to no of servers 
- [x] Use a fixed thread pool
- [ ] Explore Reload Status UI button. It shouldn't trigger the call for both reloadStatusOp and fetchTableJobs when only checking list of jobs
