### ISSUE TITLE
After the server restart

### ISSUE THREAD

**Issue by dongyanfeng** [apache/pinot#25]
Hang up a server node, restart data quantity is not correct, the query of the amount of data, sometimes return values is correct, sometimes return less than the correct values, all the tables are the situation.

**Comment by fx19880617** [comment]
Hi, could you provide the number of server instances you have, and how many replicas of your data?

**Comment by dongyanfeng** [comment]
6 server node, 6 broker node and the set config: "replication" : "3" .
thanks !

**Comment by dongyanfeng** [comment]
Query the data sometimes more sometimes less, more is correct

**Comment by dongyanfeng** [comment]
I found a phenomenon, help to think about this question。
Set the replication value is 3, there are three kinds of query are values.
Set the replication value is 2, there are two kinds of query are values.

**Comment by kishoreg** [comment]
Do you have real-time or only offline

**Comment by dongyanfeng** [comment]
real-time and offline ,but offline is no data

**Comment by fx19880617** [comment]
Since you have 3 replications, when you shut down one node, will query
results consistent? Or this only happens when you restart one node?
If the later scenario, maybe the reason is brokers don't reconnect to
server node. Another quick validation is bouncing brokers to see if the
results match.



On Wednesday, July 1, 2015, dongyanfeng <notifications@github.com> wrote:

> I found a phenomenon, help to think about this question。
> Set the replication value is 3, there are three kinds of query are values.
> Set the replication value is 2, there are two kinds of query are values.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkedin/pinot/issues/25#issuecomment-117935745>.
>


-- 
Xiang Fu
Senior Software Engineer
LinkedIn Corp.
Mountain View, CA, USA
Mobile:1-678-667-6968

**Comment by dongyanfeng** [comment]
Has nothing to do with the restart the server node, apparently associated with replicas。

**Comment by kishoreg** [comment]
hi,

can you hop on to gitter https://gitter.im/linkedin/pinot.

**Comment by dongyanfeng** [comment]
yes,i can

**Comment by dongyanfeng** [comment]
Repeat the test again and again.The above problem is after the restart the server nodes。
