### ISSUE TITLE
Config to make realtime non-winner servers download the segment instead of build

### ISSUE THREAD

**Issue by npawar** [apache/pinot#4345]
During realtime consumption, when the rows/time threshold is reached, one winner is chosen among all replicas. This winner builds the segment, uploads it to the controller. After this, the segment metadata is updated, and ideal state is updated. The ideal state update sends a CONSUMING-> ONLINE state transition to all replicas. Based on the code in LLRealtimeSegmentDataManager::goOnlineFromConsuming, each replica is given 10 minutes for the consuming thread to die. During this time, the consumers are either asked to catchup and build segment or discard and download segment. After this is completed (build or download), the replica can mark itself ONLINE. 
The time it takes for the replica to be marked ONLINE, varies depending on which of these paths it was asked to take. For the winner server, the time will be the least, as it has already built segment, and it will come up ONLINE the fastest. For servers asked to download, the time will be slightly more than the winner (mostly dependent on network speed). For servers asked to build their own segment, this time will be dependent on segment build time. Segment builds can become time consuming operations, depending on data size, indexing, sorting, consumption time, etc.  As a result, they can take much longer to come up ONLINE.
We might encounter a significant amount of time, when only 1 replica is ONLINE to serve traffic, and hence have to lift all the load by itself.

On way to solve this problem is to add a config, to make non-winner servers always download the segment instead of rebuilding. This is advantageous in more ways, as we will avoid the heap penalty of rebuilding, sorting, making inverted indexes, and simply download the ready made segment.

@mcvsubbu @Jackie-Jiang

**Comment by kishoreg** [comment]
What is the typical time taken in CONSUMING -> ONLINE state transition. This will create additional network load on the controllers.

With Jackie's change in https://github.com/apache/incubator-pinot/pull/4338, we don't need this change right?

If we really need this feature, it's better to make the wait time configurable right? 10 Minutes to 30 seconds to catch up.

**Comment by mcvsubbu** [comment]
@kishoreg making the wait-time configurable will not help if the consuming thread has already started building the segment. It cannot be interrupted when the transition is received,and the only option is to wait it out.
Jackie's change in #4338 is being evaluated in production, and yes, if it works, this change is not needed for performance. But it *is* needed for freshness. Otherwise, for a use case that takes order of  mins to build a segment we will be serving stale data in the meantime.
This change has already been tried out in production, and the results are promising.

Yes, it will create additional load on the controllers (actually, on the storage). That is why this is a table configuration, to be turned on in tables on a need-basis that satisfy multiple conditions. In our produciton scenarios. we have not felt the need for any table other than one, for this feature. The one table has 10 replicas, a very high qps and low latency requirement (< 100ms in 99th percentile), low memory foot-print, and takes minutes to build segments. We have tried out other things like building segments sooner, etc. didn't work.

The idea here is to let the controller decide whether a server should be downoading the segment or building one. In the initial version it will be a brute-force "DISCARD" return from the controller, which causes the server to just download the segment. In the medium term (or even in the first PR) we can have the controller return KEEP for 50% of the hosts, and DISCARD for the other 50%. In future, we can make more intelligent decisions.

**Comment by Jackie-Jiang** [comment]
@kishoreg With this extra config, it can reduce the freshness lag caused by my change as the CONSUMING -> ONLINE state transition time can be reduced.

**Comment by npawar** [comment]
Some options we are considering:
1. A table level config
```
segmentsConfig: {
  downloadConfig: {
    mode: DEFAULT or ALWAYS_DOWNLOAD or ALWAYS_BUILD or AUTOTUNE
   // additional config, such as replicas percentage or thresholds, build times, segment size etc
  }
}
```
The controller will read this config, and accordingly decide the response to send to a replica. The response state will not change. We can add a `boolean` field in the SegmentCompletionProtocol.Response called `download`. We can set this in the Response from SegmentCompletionProtocol.SegmentCompletionFSM::segmentConsumed. This can be as simple as reading table config and setting the boolean to begin with. Later on, we can evolve this to reading more signals, and sending separate responses to each replica
2. Controller level config, with list of tables to enable
The implementation details will be similar as option 1. Only difference will be how the config is fetched. We will not be able to add table specific fine tuning if we need to
3. Server level config
Boolean to enable "always download" on the server. This can be read directly in the PartitionConsumer::run method, in the KEEP case, and we will accordingly avoid building segment.

**Comment by mcvsubbu** [comment]
To start with, we can just have the entire logic in the controller?

The config can be:
`
segmentsConfig: {
  "downloadsConfig": {
     "percentDownloads": <integer> 
  }
}
`
For the first checkin, honor only 100% (or, treat any setting as 100%). Basically, the controller will ask server to download if the config is set.

If the server sends DISCARD, this will happen, right? Alternatively, we can introduce a new response code of DOWNLOAD, or add a parameter in KEEP (I like the latter, makes it more extensible).

**Comment by npawar** [comment]
Yes, agree with adding a parameter in the SegmentCompletionProtocol.Response (instead of new type of status). This is the option 1 above.
I like the suggestion of returning DISCARD the most . It seems cleaner and a better flow to me than  adding a parameter. What do you think? 
`percentDownloads` is a good idea. But i don't feel we should have it in the very first PR. Because we are not clear on how we want to evolve this. I don't want to add something that we might change our minds about.. Whereas the `mode` field, we will need it definitely
