### ISSUE TITLE
Udf support

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#552]
Some sample queries:
1. one to one event transform(select/ordering/no aggregation)
   SELECT to_hour(localTimeConverter(trip_time, city_name)) as local_hour, trip_id, city_name FROM mytable WHERE drvier_id = "xxxx" order by local_hour DESC limit 1000
2. Aggregation only
   // Get max/min trip duration for a driver
   SELECT to_hours(max(trip_end_ts - trip_start_ts)), to_minutes(min(trip_end_ts - trip_start_ts)) FROM mytable where drvier_id = "xxxx"
3. Aggregation group by
   SELECT sum(trip_fare), to_hour(convert_to_local_time(trip_time, city_name)) as local_hour, city_name FROM mytable group by by to_hour(convert_to_local_time(trip_time, city_name)), city_name
4. javascript based udf for runtime quick validation

**Comment by mayankshriv** [comment]
Thank you @fx19880617 for requesting for UDF support in Pinot. I am currently exploring the idea of supporting what I'd like to call Transform operators, and feel that supporting UDF's would fit well within the idea of transforms. I am sharing my initial idea in a [design doc](https://github.com/linkedin/pinot/wiki/Expressions-&-UDF-support) that I started writing. Let's use this thread to shape up & refine the idea, and discuss how UDF's fit into it.

**Comment by fx19880617** [comment]
Very impressive write up @mayankshriv !

Overall looks good to me, have two points here:
1. Will function be able to take multiple constants as parameters? like convert_from_timezone_to(ts, 'UTC', 'PDT') ? The reason is antlr parsed column name to IDENTIFIER and constant(string/numbers) to literal. 
This may causing backward compatible issue for PQL query parser.
 
2. Also I think the semantics of "select func(...) AS some_func ..." need to be support in this case to make results naming more meaningful.

**Comment by kishoreg** [comment]
+1 to support aliasing. This as can be done independently of UDF support
right? Probably better to do that first before starting on UDF.
