### ISSUE TITLE
Pinot column to support no dictionary indexing

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#654]
The basic idea is dictionary may not benefit too much for the columns with very high cardinality like gps points/uuid, we may just store raw double/string.

This required change either interface of getting object from forward index or we can make a NoopDictionary which point to the foward indexes for raw value fetch.

**Comment by raviarin** [comment]
This has a been a long outstanding item in our back log :). I like the idea of NoOp dictionary as it does not change the interfaces. However, JF or Mayank might have thought about this a bit more than me. Should be worth a discussion with them.

**Comment by kishoreg** [comment]
Thanks for starting the issue @fx19880617. This is critical for improving scan performance on high cardinality columns e.g metrics and string columns where maintaining dictionary does not make sense.

While our initial goal was to not expose Dictionary outside of data source, parts of existing code make direct reference to Dictionary. The No-Op dictionary can only work for columns with columns of int data type.

We should use this to fix the usage of dictionary class outside of data source. This will involve changes across all operators but I don't see any other option. But I think it's worth the effort, it will allow us to improve performance drastically in some scenarios.

Here are my thoughts.

Most operators work on Blocks and use the BlockValSet to read values. But unfortunately, they first read the dictionary ids 
`  void readIntValues(int[] inDocIds, int inStartPos, int inDocIdsSize, int[] outDictionaryIds, int outStartPos);`

and then use dictionary interface to read actual values.
  ```
void readIntValues(int[] dictionaryIds, int startPos, int limit, int[] outValues, int outStartPos);
  void readLongValues(int[] dictionaryIds, int startPos, int limit, long[] outValues, int outStartPos);
  void readDoubleValues(int[] dictionaryIds, int startPos, int limit, double[] outValues, int outStartPos);
  void readFloatValues(int[] dictionaryIds, int startPos, int limit, float[] outValues, int outStartPos);
  void readStringValues(int[] dictionaryIds, int startPos, int limit, String[] outValues, int outStartPos);
```
We need to provide reading the actual value on block val set. This allows the data source to handle dictionary/no dictionary case transparently.

The downside of this is that some of the operators might benefit by using raw dictionaryId instead of actual value. Which means we have to provide both methods on blockValSet readDictionaryIds and readValues.

I will give it a try and see how the interfaces look. We also have some usage of dictionary in filter phase but its much easier to push down that functionality to data source.

**Comment by mayankshriv** [comment]
Closing this issue as No-Dictionary indexing support was added back in Jan 2017: https://github.com/apache/incubator-pinot/pull/932
