### ISSUE TITLE
Enhancing JSON index to provide free text search on string value space

### ISSUE THREAD

**Issue by kotharironak** [apache/pinot#6752]
I tried the JSON index support in the latest `apache-pinot-0.7.0`and observed that I was not able to do a free text search on `json` value space. 

As shown in the below example, I was able to do an equality search as in Q1. But, I was not able to do the `text_match` kind of search as in Q2.
```
Table = json_doc_example
Example data with 3 rows:
id_col, json_doc_col
"1234", {"message": "too many retries"}
"1235", {"message": "error sql timeout"}
"1236", {"message": "too large filter"}
```

Query Q1: returns -> [1236]
```
select * from json_doc_example JSON_MATCH(json_doc_col, 'message=''too lareg filter''') 
```

Query Q2: returns empty result (was expecting it to return : [1234, 1236])
```
select * from json_doc_example JSON_MATCH(json_doc_col, 'message=''too''') 
```

- Can we add similar `text_match` support on `json` value space ? or 
- is it recommended to use both text index + json index for such use case on that column?

**Comment by Jackie-Jiang** [comment]
Json index only supports exact match. In order to do text match, you need to use `jsonExtractScalar`, e.g. `select ... where jsonExtractScalar(json_col, '$.message', 'STRING') like 'too.*'. The performance might not be very good because we have to scan and reconstruct the json from the json string.
You can add text index on the json string column, but that will treat the json string as regular string.
For the example above, extracting `message` field as a separate column will give much better performance.

**Comment by Jackie-Jiang** [comment]
Regexp like is supported with #12568
