### ISSUE TITLE
Issues in generating the segment when working with Fixed type in SegmentNameGeneratorSpec

### ISSUE THREAD

**Issue by Manis99803** [apache/pinot#8068]
Issue:

Currently, with a Fixed type in the Pinot SegmentNameGenerator, we are able to generate a segment with an user-defined name. However, there is some issue with respect to this when we want to generate more than one segment.

For Example:
Let's say we have 5 different CSVs and we are trying to push these CSVs to the Pinot Offline table. The ingestion job has the following configuration:
```
segmentNameGeneratorSpec:
  configs:
    segment.name: SEGMENT
  type: fixed
```
So the expectation was that, if we try to push 5 CSVs to the Pinot table we would have 5 segments with the following names:
SEGMENT_0
SEGMENT_1
SEGMENT_2
SEGMENT_3
SEGMENT_4

However, we see only one segment getting created with the name "SEGMENT". And the data this segment would have will be the data present in the last CSV in our case that becomes (5th one).

On checking the [code link](https://github.com/apache/pinot/blob/3f93cfb93a386ee3e8bd108ffe34814b734575e9/pinot-segment-spi/src/main/java/org/apache/pinot/segment/spi/creator/name/FixedSegmentNameGenerator.java#L36), it looks like in case of Fixed naming scheme sequenceId is not getting appended to the segment name due to which every time same segment name is getting generated. 

Let me know if the analysis is right then I can work on the fixing it.

**Comment by Jackie-Jiang** [comment]
Fixed segment name generator will ignore the sequence id. In order to include the sequence id, you may use the `simple` segment name generator, and set the name prefix to `SEGMENT`

**Comment by jackjlli** [comment]
Both `SimpleSegmentNameGenerator` and `NormalizedDateSegmentNameGenerator` respect the sequence Id. You can either set `simple` or set `normalizedDate` to the ingestionConfig of your table config.

**Comment by Manis99803** [comment]
In case of `SimpleSegmentNameGenerator` sequence Id is respected. However, the segment names also have the timestamp in them.

For Example: 
If I create a table "user" and push data to it and I am going with "Simple" SegmentNameGeneratingScheme and generating 2 different segments. The names would be as follows:

user_OFFLINE_1643169382000_1643169385000_0
user_OFFLINE_1643169386000_1643169389000_1

The problem I am trying to highlight is suppose I want to create 2 segments and a user has defined a fixed name say "SEGMENT" and the user wants to have sequenceId to the segments, then that is not possible:
Expectation:
SEGMENT_0
SEGMENT_1

With the current implementation, we will have only 1 segment getting created with a fixed name "SEGMENT"

**Comment by jackjlli** [comment]
@Manis99803 For APPEND use cases, these timestamps are the minmax value of the time column in your raw input file, which differentiates which batch of jobs the segments belong to. Without the values of time column appeared in the segment name, there is no way to tell when this batch of segments it belong to. What's worse, since segment name is the identifier for segment, if the minmax value is missing from the segment name, the newer batch of segments will replace the existing segments in the table, since the segment name would be the same (e.g. old and new segment name are both called `user_OFFLINE_0`).
Unless you want to use REFRESH type for the table, where the time column field isn't needed, then you can skip the minmax value in the segment name.

**Comment by Manis99803** [comment]
@jackjlli, Thanks for pointing this out. I understand the entire use case now, let me go ahead and close this issue.
