### ISSUE TITLE
RealtimeNonReplicaGroupSegmentAssignmentTest.testRelocateCompletedSegments is flaky

### ISSUE THREAD

**Issue by richardstartin** [apache/pinot#8791]
https://github.com/apache/pinot/runs/6627855246?check_suite_focus=true

This test failed one time out of ten runs locally

**Comment by Jackie-Jiang** [comment]
A lot of test failures are not easy to re-produce locally. Usually they failed due to very limited resources provided by the CI VMs: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
If we can setup a VM with very limited resource (e.g. 2 CPU cores), it should be much easier to reproduce the issue
