### ISSUE TITLE
OfflineGRPCServerIntegrationTest is flaky

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#8968]
https://github.com/apache/pinot/runs/7014263352?check_suite_focus=true

**Comment by walterddr** [comment]
Exit code 137 - Process was killed by [Linux OOM Killer](http://www.oracle.com/technetwork/articles/servers-storage-dev/oom-killer-1911807.html) because you are low on resources on the machine.

this likely is due to memory leak on GRPC integration test. difficult to debug without a core dump. do we have access to interactive GHA by default?

**Comment by walterddr** [comment]
closing after #8997
