### ISSUE TITLE
[multistage] timeout issue running multi-table join on limited resource

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#9563]
based on https://github.com/apache/pinot/pull/9541

- we've observe severe timeout issues when running with SSB test queries with `-XX:ActiveProcessorCount=2`
This is highly likely due to thread thrashing.

We should either 
- early terminate on resource contention. or 
- make sure there's enough resource allocated for executing these multi-table joins, or
- improve planner resource anticipation

**Comment by agavra** [comment]
This is caused because there's a shared thread pool that's sized using the number of available cores and is used for both remote and local execution. Specifically, if there's more `MailboxReceiveOperator` tasks than there are threads in the pool it will block all threads (as the operator is a blocking call).

See #9615 as a potential workaround.

**Comment by walterddr** [comment]
i think this can be closed and merged with #9615 . we've already identified the issue and also we already saw the TODO has been added.
